import Foundation

/// Pure projector from `[Account]` (the source of truth) to the
/// three kinds of managed files keychord owns under
/// ~/.config/keychord/:
///
///   * ssh_config.managed         — all SSH Host blocks
///   * gitconfig.managed          — global [user], all url rewrites,
///                                   and [includeIf] pointers for
///                                   scoped accounts
///   * gitconfig-<uuid>.managed   — one per scoped account, with
///                                   [user] + [core] sshCommand
///
/// `project(_:)` is pure and deterministic so tests can pin exact
/// content. `write(_:)` writes the output to disk.
/// `regenerate(accounts:paths:)` is the one-call entry point:
/// it builds, writes, installs the Include lines in the user's
/// ~/.ssh/config + ~/.gitconfig, and deletes sub files that no
/// longer belong to any account.
enum AccountProjector {

    // MARK: - Output types

    struct ProjectedOutput: Equatable, Sendable {
        let sshConfig: String
        let gitConfig: String
        let subFiles: [SubFile]

        struct SubFile: Equatable, Sendable {
            let accountID: UUID
            let content: String
        }
    }

    struct ManagedPaths: Sendable, Equatable {
        var sshManaged: String
        var gitManaged: String
        var userSSHConfig: String
        var userGitConfig: String

        /// Directory that hosts sshManaged + gitManaged + sub files.
        var managedRoot: String {
            (sshManaged as NSString).deletingLastPathComponent
        }

        func subFilePath(for id: UUID) -> String {
            "\(managedRoot)/gitconfig-\(id.uuidString).managed"
        }

        static var `default`: ManagedPaths {
            let home = NSHomeDirectory()
            return ManagedPaths(
                sshManaged: "\(home)/.config/keychord/ssh_config.managed",
                gitManaged: "\(home)/.config/keychord/gitconfig.managed",
                userSSHConfig: "\(home)/.ssh/config",
                userGitConfig: "\(home)/.gitconfig"
            )
        }
    }

    // MARK: - Pure projection

    static func project(
        _ accounts: [Account],
        generatedAt: Date = Date(),
        paths: ManagedPaths = .default
    ) -> ProjectedOutput {
        let timestamp = Self.iso8601(generatedAt)
        let headerSSH = """
        # AUTO-GENERATED BY keychord. Edit via the app or accounts.json.
        # Last regenerated: \(timestamp)

        """
        let headerGit = """
        # AUTO-GENERATED BY keychord. Edit via the app or accounts.json.
        # Last regenerated: \(timestamp)

        """

        // SSH Host blocks — one per account with a non-empty alias/key.
        var ssh = headerSSH
        for account in accounts {
            guard !account.sshAlias.isEmpty, !account.keyPath.isEmpty else { continue }
            ssh += Self.formatSSHHost(account)
            ssh += "\n"
        }

        // Main gitconfig.managed: global [user] (last-wins), url
        // rewrites grouped by target, includeIf for scoped accounts.
        var git = headerGit

        let globalAccounts = accounts.filter { $0.scope == .global && !$0.gitUserName.isEmpty }
        if let globalAccount = globalAccounts.last {
            git += "[user]\n"
            git += "\tname = \(globalAccount.gitUserName)\n"
            git += "\temail = \(globalAccount.gitUserEmail)\n\n"
        }

        // Group rewrites by target (the `to` URL prefix) so multiple
        // insteadOf values land under one [url "..."] block.
        var rewritesByTarget: [String: [String]] = [:]
        for account in accounts {
            for rule in account.urlRewrites {
                rewritesByTarget[rule.to, default: []].append(rule.from)
            }
        }
        for target in rewritesByTarget.keys.sorted() {
            let froms = rewritesByTarget[target] ?? []
            git += "[url \"\(target)\"]\n"
            for from in froms {
                git += "\tinsteadOf = \(from)\n"
            }
            git += "\n"
        }

        // Scoped accounts → includeIf in main + a per-account sub file.
        var subs: [ProjectedOutput.SubFile] = []
        for account in accounts {
            guard case .gitdir(var dir) = account.scope else { continue }
            if !dir.hasSuffix("/") { dir += "/" }
            let subPath = paths.subFilePath(for: account.id)
            let subTildePath = Self.toTilde(subPath)

            git += "[includeIf \"gitdir:\(dir)\"]\n"
            git += "\tpath = \(subTildePath)\n\n"

            var sub = "# AUTO-GENERATED BY keychord for account \(account.id.uuidString) (\(account.label))\n\n"
            if !account.gitUserName.isEmpty {
                sub += "[user]\n"
                sub += "\tname = \(account.gitUserName)\n"
                sub += "\temail = \(account.gitUserEmail)\n\n"
            }
            if !account.keyPath.isEmpty {
                sub += "[core]\n"
                sub += "\tsshCommand = ssh -i \(Self.toTilde(account.keyPath)) -o IdentitiesOnly=yes\n"
            }
            subs.append(ProjectedOutput.SubFile(accountID: account.id, content: sub))
        }

        return ProjectedOutput(sshConfig: ssh, gitConfig: git, subFiles: subs)
    }

    // MARK: - Write to disk

    static func write(
        _ output: ProjectedOutput,
        paths: ManagedPaths = .default
    ) throws {
        let managedRoot = paths.managedRoot
        try FileManager.default.createDirectory(
            atPath: managedRoot,
            withIntermediateDirectories: true
        )

        try output.sshConfig.write(
            toFile: paths.sshManaged,
            atomically: true,
            encoding: .utf8
        )
        try output.gitConfig.write(
            toFile: paths.gitManaged,
            atomically: true,
            encoding: .utf8
        )

        // Reconcile sub files: delete those no longer in output, write
        // the current ones.
        let desiredPaths = Set(output.subFiles.map { paths.subFilePath(for: $0.accountID) })
        if let existing = try? FileManager.default.contentsOfDirectory(atPath: managedRoot) {
            for name in existing where name.hasPrefix("gitconfig-") && name.hasSuffix(".managed") {
                let fullPath = "\(managedRoot)/\(name)"
                guard desiredPaths.contains(fullPath) == false else { continue }
                try? FileManager.default.removeItem(atPath: fullPath)
            }
        }
        for sub in output.subFiles {
            let subPath = paths.subFilePath(for: sub.accountID)
            try sub.content.write(toFile: subPath, atomically: true, encoding: .utf8)
        }
    }

    // MARK: - End-to-end regenerate

    /// Build → write → install include lines. The one call that the
    /// window's save action uses after every mutation.
    static func regenerate(
        accounts: [Account],
        paths: ManagedPaths = .default,
        generatedAt: Date = Date()
    ) throws {
        let output = project(accounts, generatedAt: generatedAt, paths: paths)
        try write(output, paths: paths)

        try IncludeInstaller.installSSHInclude(
            targetPath: paths.userSSHConfig,
            managedPath: paths.sshManaged
        )
        try IncludeInstaller.installGitInclude(
            targetPath: paths.userGitConfig,
            managedPath: paths.gitManaged
        )
    }

    // MARK: - Formatting helpers

    static func formatSSHHost(_ account: Account) -> String {
        switch account.sshPort {
        case .port22:
            return """
            Host \(account.sshAlias)
            \tHostName github.com
            \tPort 22
            \tUser git
            \tIdentityFile \(toTilde(account.keyPath))
            \tIdentitiesOnly yes
            """ + "\n"
        case .port443:
            return """
            Host \(account.sshAlias)
            \tHostName ssh.github.com
            \tPort 443
            \tUser git
            \tIdentityFile \(toTilde(account.keyPath))
            \tIdentitiesOnly yes
            \tHostKeyAlias github.com
            """ + "\n"
        }
    }

    static func toTilde(_ abs: String) -> String {
        let home = NSHomeDirectory()
        if abs.hasPrefix(home) {
            return "~" + abs.dropFirst(home.count)
        }
        return abs
    }

    private static func iso8601(_ date: Date) -> String {
        let fmt = ISO8601DateFormatter()
        fmt.formatOptions = [.withInternetDateTime]
        return fmt.string(from: date)
    }
}
